GET http://localhost:8000/member/member/count
Accept: application/json

{
"token": "123"
}
###
POST http://localhost:8000/member/member/register
Content-Type: application/json

{
  "mobile": "123456789"
}

###
POST http://localhost:8000/member/member/sendCode
Content-Type: application/json

{
  "mobile": "13812147098"
}

###

POST http://localhost:8000/member/member/login
Content-Type: application/json

{
  "mobile": "13812147098",
  "code": "8888"
}

###